### ISSUE TITLE
Move docs folder from organisation-internal

### ISSUE THREAD

**Issue by jamalv** [teamforus/organisation#11]
@maxvisser, could you use your Git voodoo magic to move https://github.com/teamforus/organisation-internal/tree/master/docs to this repo?

**Comment by maxvisser** [comment]
this is within my skillset. Will do this tomorrow

**Comment by maxvisser** [comment]
i pushed the docs folder from internal to this repo. There were some issue templates stored in the root of this repository. Do you want to keep those?

**Comment by jamalv** [comment]
no, this is fine, thx!
