### ISSUE TITLE
Branching / pull request / review strategy

### ISSUE THREAD

**Issue by jamalv** [teamforus/organisation#3]
The current proposal is as follows (based on the link and image below):

### Development:

1. Developers will work in a separate (feature) branch. 
2. When the feature is done, they will add it to develop via a pull request. 

## Release:
1. When develop is ready to be deployed, a release branch e.g. release/v1.1 will be created from develop. 
2. A pull request will be created from the release branch to the master branch.
3. The pull request will be reviewed and tested.
4. Bugfixes can be made on the release branch, development can continue.
5. If all is good the release will be tagged, merged to master and deployed.

![git-model 2x](https://user-images.githubusercontent.com/30194799/39862230-6af1fefa-5443-11e8-90ea-d236120bbd72.png)

from: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by maxvisser** [comment]
![image](https://user-images.githubusercontent.com/10818702/40364651-2c6cc28e-5dd3-11e8-9749-afb1c28949fa.png)

Where should @GerbenBosschieter test? In pull request 1 or 2?

**Comment by jamalv** [comment]
I would say number 2; since the idea is that nothing will be merged from develop anymore. Only bug fixes that will be made directly in the release branch (so the pull request will be automatically updated)

**Comment by maxvisser** [comment]
so why do you pull request from dev to release if there is no quality check there?

**Comment by jamalv** [comment]
When it is time to prepare a release, we'll branch from develop e.g. release-1.3, so there is no quality check there. Then from release-1.3 a pull request can be made into master, where it can be tested.

Now I'm thinking about it bug fixes should probably not be made directly on the release branch anyway. From looking at the article the suggestion seems to be to make a branch hotfix-xxx that can then be merged into both develop and release. When release is fully tested, the last commit can be tagged and the pull request can be approved.

**Comment by maxvisser** [comment]
I agree. with open source development it makes more sense to also check pull request on 1.

You can decide if a feature is becoming part of a release can happen there.

**Comment by jamalv** [comment]
Agreed, it seems like a good strategy. We can start implementing it and see if it works for us in practice.

**Comment by maxvisser** [comment]
I think we all were in consensus that this was the right path to go. (best practice even).
Let try it out.
