### ISSUE TITLE
RFA002: Splitting up Forus.io and Me project boards.

### ISSUE THREAD

**Issue by jamalv** [teamforus/organisation#9]
Would it make sense to split up the project boards into forus.io and me? In this phase there is still a lot of overlap in the projects, but there are mostly two different teams working on those projects.

**Comment by martijndoornik** [comment]
I see three boards: Forus.io, Me App and Foundation/Organisation

**Comment by jastam** [comment]
Where exactly does kindpakket fit in?

**Comment by maxvisser** [comment]
This is implemented.
